import type { Chat, Folder } from '#/telegram/types'

export const FIXTURE_FOLDERS: Folder[] = [
  {
    id: 2,
    title: 'Работа',
    emoticon: '💼',
    flags: {
      contacts: false,
      nonContacts: false,
      groups: true,
      broadcasts: false,
      bots: false,
      excludeMuted: false,
      excludeRead: false,
      excludeArchived: true,
    },
    includeCount: 2,
    excludeCount: 1,
    pinnedCount: 1,
    readOnly: false,
  },
  {
    id: 3,
    title: 'Учёба',
    emoticon: '📚',
    flags: {
      contacts: false,
      nonContacts: false,
      groups: false,
      broadcasts: true,
      bots: false,
      excludeMuted: true,
      excludeRead: false,
      excludeArchived: false,
    },
    includeCount: 1,
    excludeCount: 0,
    pinnedCount: 0,
    readOnly: false,
  },
  {
    id: 4,
    title: 'Общий чатлист',
    emoticon: '🔗',
    flags: {
      contacts: false,
      nonContacts: false,
      groups: false,
      broadcasts: false,
      bots: false,
      excludeMuted: false,
      excludeRead: false,
      excludeArchived: false,
    },
    includeCount: 1,
    excludeCount: 0,
    pinnedCount: 0,
    readOnly: true,
  },
]

export const FIXTURE_CHATS: Chat[] = [
  {
    id: 1,
    peerId: 1,
    kind: 'saved',
    title: 'Vasiliy',
    isPinned: false,
    isArchived: false,
    isMuted: false,
    unreadCount: 0,
    isSelf: true,
    canDelete: true,
    canLeave: false,
    canBlock: false,
    folders: {},
  },
  {
    id: 2,
    peerId: 2,
    kind: 'user',
    title: 'Команда',
    username: 'team_friend',
    isPinned: true,
    isArchived: false,
    isMuted: false,
    unreadCount: 3,
    isSelf: false,
    canDelete: true,
    canLeave: false,
    canBlock: true,
    folders: { 2: 'pinned' },
  },
  {
    id: 3,
    peerId: 3,
    kind: 'group',
    title: 'Проектная группа',
    isPinned: false,
    isArchived: false,
    isMuted: true,
    unreadCount: 0,
    isSelf: false,
    canDelete: false,
    canLeave: true,
    canBlock: false,
    folders: { 2: 'include' },
  },
  {
    id: 4,
    peerId: 4,
    kind: 'channel',
    title: 'Новости TanStack',
    username: 'tanstack_news',
    isPinned: false,
    isArchived: false,
    isMuted: false,
    unreadCount: 12,
    isSelf: false,
    canDelete: false,
    canLeave: true,
    canBlock: false,
    folders: { 3: 'include', 4: 'include' },
  },
  {
    id: 5,
    peerId: 5,
    kind: 'bot',
    title: 'Support Bot',
    username: 'support_bot',
    isPinned: false,
    isArchived: true,
    isMuted: true,
    unreadCount: 0,
    isSelf: false,
    canDelete: true,
    canLeave: false,
    canBlock: true,
    folders: { 2: 'exclude' },
  },
  {
    id: 6,
    peerId: 6,
    kind: 'supergroup',
    title: 'Архив обсуждений',
    isPinned: false,
    isArchived: true,
    isMuted: false,
    unreadCount: 0,
    isSelf: false,
    canDelete: false,
    canLeave: true,
    canBlock: false,
    folders: {},
  },
]
