/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlockedRouteImport } from './routes/blocked'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MatrixRouteImport } from './routes/matrix'
import { Route as SettingsRouteImport } from './routes/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlockedRoute = BlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrixRoute = MatrixRouteImport.update({
  id: '/matrix',
  path: '/matrix',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blocked': typeof BlockedRoute
  '/login': typeof LoginRoute
  '/matrix': typeof MatrixRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blocked': typeof BlockedRoute
  '/login': typeof LoginRoute
  '/matrix': typeof MatrixRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blocked': typeof BlockedRoute
  '/login': typeof LoginRoute
  '/matrix': typeof MatrixRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/blocked' | '/login' | '/matrix' | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blocked' | '/login' | '/matrix' | '/settings'
  id: '__root__' | '/' | '/blocked' | '/login' | '/matrix' | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlockedRoute: typeof BlockedRoute
  LoginRoute: typeof LoginRoute
  MatrixRoute: typeof MatrixRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocked': {
      id: '/blocked'
      path: '/blocked'
      fullPath: '/blocked'
      preLoaderRoute: typeof BlockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matrix': {
      id: '/matrix'
      path: '/matrix'
      fullPath: '/matrix'
      preLoaderRoute: typeof MatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlockedRoute: BlockedRoute,
  LoginRoute: LoginRoute,
  MatrixRoute: MatrixRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
